version: "3.9"
services:
   db:
      image: postgres:14
      ports: 
      - "${DATABASE_PORT}:${DATABASE_PORT}"
      volumes:
      - type: bind
        source: /tmp/postgres-data
        target: ${PGDATA}
      environment:
        POSTGRES_USER: ${PGUSER}
        POSTGRES_DB: ${PGDATABASE}
        POSTGRES_PASSWORD: ${PGPASSWORD}
        PGDATA: ${PGDATA}
      networks:
         node_net:
            ipv4_address: ${DATABASE_IP}
   players:
      build:
        context: .  
      image: voliboli-backend:latest
      ports: 
      - ${PORT}:${PORT}
      environment:
        DATABASE_IP: ${DATABASE_IP}
      depends_on:
      - db
      networks:
         node_net:
            ipv4_address: 172.34.1.3

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.34.0.0/16
