"""Initial migration

Revision ID: e7b326d65d8f
Revises: 
Create Date: 2022-09-05 12:49:45.006527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b326d65d8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_model', sa.Column('date_team', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'player_model', ['id_player'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_model', type_='unique')
    op.drop_column('player_model', 'date_team')
    # ### end Alembic commands ###
